print("HELLO WORLD")
print("HELLO"+" WORLD")
print("HELLO\nWORLD")
phrase="iron man"
character_name="tony stark"
print("The "+ phrase+" suit was made by "+character_name+ ".")
print("he is 34 years old")
character_age="34"
print("he is "+ character_age+" years old.")
character_age=34
print("he is "+ str(character_age)+" years old.")
phrase="ALMANAC"
print (phrase)
print("CONCATONING-its the process of joining two strings together in python....roughly speaking.\nan example is shown below.")
print(phrase+"  is a really cool and research based comapny.")
print("Now we speak about functions, its done along with using phrases.")
print("These are a special block of code that we use to run, that will peform a specific operation for us")
print("we can use functions to modify our strings, and also to get information about our strings")
print("for examample "+phrase.lower())
print("for example "+phrase.upper()) 
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print("now we're going to select individual characters in a string")
print(phrase[0])
print(phrase[4])
print("next is the INDEX function:tel us where a specific string is located in another string")
print("giving a certain value to a function is called passing a PARAMETER. You'll hear about this a LOT")
print(phrase.index("A"))
print(phrase.index("L"))
print(phrase.index("MAN"))
phrase = "ALMANAC company"
phrase = phrase.replace("ALMANAC", "Infinity")
print(phrase)
print("for examample "+phrase.lower())
print("for example "+phrase.upper()) 
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[4])
print("lets get to working with numbers on python")
print(2)
print(2+4+10*4)
print("next up is the modulus operator. See, here we get the remainder when a certain number is divided by another.Look below")
print(10%3)
print(9%3)
my_num=5
print(my_num)
print("everytime you want to print out a number next to a sentence and its being used multiple times...then you goin with the string method is best.Like this")
print(str(my_num)+" is my favorite number")
my_num=-5
print(abs(my_num))
print(pow(3,2))
print(max(3,2))
print(min(3,2))
print(round(3.2))
print(round(3.8))
from math import * 
print(floor(3.8))
print(ceil(3.8))
print(sqrt(36))
print(sqrt(3123))
print("there are a lot of math functions in python aside from the ones mentoned above. So go look them up")
